name: CI-CodeBuild 🚀

on:
  workflow_dispatch:

jobs:
  lint:
    environment: test environment
    runs-on:
      - codebuild-test-gha-approval-${{ github.run_id }}-${{ github.run_attempt }}
      - deployment-status-override:true
    steps:
      - name: test commands
        run: echo "HELLO WORLD"
