name: CI-CodeBuild 🚀

on:
  workflow_dispatch:

jobs:
  lint:
    environment: test environment
    # environment: no-approval-environment
    runs-on:
      - codebuild-test-env-permissions-beta-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: test commands
        run: echo "HELLO WORLD"
